import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SymbolTable from '../components/symbolTable'
import Navbar from '../components/Navbar'
import { gql } from "@apollo/client";
import client from "../apollo-client";


const Home: NextPage = ({ stocks }: any) => {
  console.log('stocksdata', stocks)
  return (
    <div>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Tweest!</a>
          </h1>
          <SymbolTable stocks={stocks} />
        </main>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const response = await client.query({
    query: gql`
      {
        getStocks {
          symbol
          timestamp
          close
        }
      }
    `,
  });
  return {
    props: {
      stocks: response,
    },
  };
}

export default Home;
