import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";
import client from "../apollo-client";
import GetLiveData from "../components/live-data-model"

const Home: NextPage = ({ stocks }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GetLiveData/>
      <main className={styles.main}>{JSON.stringify(stocks)}</main>
    </div>
  );
};
export async function getStaticProps() {
  const response = await client.query({
    query: gql`
      {
        getStocks {
          symbol
          timestamp
          close
        }
      }
    `,
  });
  return {
    props: {
      stocks: response,
    },
  };
}

export default Home;
